name: CI Pipeline

on:
  push:
    branches:
      - '**'  # This will run on pushes to any branch
  pull_request:
    branches:
      - '**'  # This will run on pull requests to any branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.8.3
        poetry install
    
    - name: Run isort
      run: poetry run isort . --check-only --diff
    
    - name: Run black
      run: poetry run black . --check --diff
    
    - name: Run flake8
      run: poetry run flake8 .
    
    - name: Run pytest
      run: poetry run pytest
  
  build-docker:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build . -t my-image:${{ github.sha }}
    
    # Optionally, you can push the image to a registry
    # - name: Push to Docker Hub
    #   run: |
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker push my-image:${{ github.sha }}
    